### PR TITLE
Lifehash, UR, categories

### PR DESCRIPTION
**Pull request by Fonta1n3**
This PR adds the ability to edit the QR label, "update" existing (supported) QR types to UR's.

Currently the app will categorize and label:
- Account Map
- QuickConnect
- SSKR Shard
- BIP39 Mnemonic
- All UR's

Currently the app will allow you to convert an existing QR from:
- plain text BIP39 mnemonic to a `crypto-seed` UR
- plain text SSKR shard to a `crypto-sskr` UR

### CODE REVIEW

**Comment by ChristopherA** [comment]
Did you want me to review this? It is still marked as a "work in progress"

**Comment by Fonta1n3** [comment]
> Did you want me to review this? It is still marked as a "work in progress"

Not yet, it's still in draft status. Should be updating later today for review and Testflight release.

**Comment by Fonta1n3** [comment]
Ping @ChristopherA ready now.

**Review by ChristopherA — APPROVED** [review]
Build ACK. Built on macOS Catalina (10.15.6), using command line tools for Xcode 11.7. Target of iPhone SE failed, but target of iPhone 11 Pro worked, as did MacOS. Did minimal testing, no regression test.

**Pull request merged**
